variables:
REACT_APP_API_URL_DEVELOPMENT: "http://192.168.1.30:1323/"
REACT_APP_API_URL_PRODUCTION: "https://bb-api.una.rest/"

stages:
  - test
  - build
  - publish
  - deploy

testing:
  stage: test
  image: node:18
  script:
    - npm install
    - npm test
  tags:
    - docker

building:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  tags:
    - docker

publish:
  stage: publish
  image: docker
  script:
    - docker build -t una_bb_ui .
  tags:
    - una_bb_ui

deploy_app:
  stage: deploy
  image: docker
  script:
    - docker run -d \
      --name una_bb_ui \
      --network apps \
      una_bb_ui
  tags:
    - una_bb_ui